# Site settings
title: Smarsh Federal Archive Documentation
email: docfeedback@smarsh.com
description: >- # this means to ignore newlines until "baseurl:"
  Comprehensive Federal Archive user documentation.
baseurl: "/federal-archive-docs" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: smarsh
github_username:  athay-docs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
